### ISSUE TITLE
Changement de serveur Mastodon

### ISSUE THREAD

**Issue by notabene** [Cerdic/mastodon#1]
Salut @Cerdic 

J'ai changé de serveur Mastodon, et celui sur lequel j'étais n'est plus disponible.

J'ai réactivé le plugin Mastodon que j'avais désactivé, or il a conservé les paramètres de l'ancien compte.

Quand je me connecte sur `/ecrire/?exec=configurer_mastodon` j'ai l'erreur suivante :

> L140: Error: "SSL: no alternative certificate subject name matches target host name 'cafe.des-blogueurs.org'" - Code: 51

(Ce qui est tout à fait correct : le domaine existe encore mais il ne pointe vers rien, j'ai la même erreur dans mon navigateur.)

L'erreur complète affichée (j'ai abrégé les chemins) :

```
L140: Error: "SSL: no alternative certificate subject name matches target host name 'cafe.des-blogueurs.org'" - Code: 51
/*001*/
/*002*/<h1 class="grostitre">Configurer Mastodon</h1>
/*003*/
/*004*/<div class="ajax">
/*005*/<?php 
/*006*/include_once("[…]/spip/ecrire/balise/formulaire_.php");
/*007*/if ($lang_select = "fr") $lang_select = lang_select($lang_select);
/*008*/inserer_balise_dynamique(balise_FORMULAIRE__dyn('FORMULAIRE_CONFIGURER_MASTODON'), array('../plugins/dist/plugins/mastodon/prive/squelettes/contenu/configurer_mastodon.html', 'html_b095476dad1af5381e5b7adcc6451b52', '', 5, 'fr'));
/*009*/if ($lang_select) lang_select();
/*010*/?>
/*011*/</div>
/*012*/
/*013*/
```

Le tableau de debug spip donne les informations complémentaires suivantes :

* Squelette : `../plugins/dist/plugins/mastodon/prive/squelettes/contenu/configurer_mastodon.html`
* Boucle : `[…]/spip/plugins/plugins/mastodon/lib/tootophp/HttpRequest.php`

Suggestion : intercepter l'erreur et fournir une option pour changer de serveur / supprimer le serveur et repartir sur la configuration vierge.

**Comment by notabene** [comment]
PS : j'ai aussi tenté de supprimer les données proprement via Liste des plugins → Désinstaller mais l'erreur persiste.

**Comment by notabene** [comment]
En local, j'ai supprimé `tmp/meta_cache.php` qui est recréé au rechargement de `ecrire/` après avoir désactivé  et je retrouve dedans le nom du serveur. Rien dans la table `spip_meta`. Là j'avoue mon inculture pour débugger. ;)

**Comment by Cerdic** [comment]
Je regarde ça asap!

**Comment by Cerdic** [comment]
Corrigé par 50b2cd3ec3f2171257cf3bc961d680b402e0d1cf (et déployé)

**Comment by notabene** [comment]
Génial, ça marche \o/
